CREATE TABLE TM_FREE_BOARD
(       TFB_SEQ         NUMBER(10) NOT NULL
,       TFB_TITLE_NM    VARCHAR2(300)
,       TFB_TEXT        VARCHAR2(4000)
,       TFB_INPUT_TY    VARCHAR2(300)
,       TFB_INPUT_NM    VARCHAR2(300)
,       TFB_INPUT_DT    DATE
,       TFB_INPUT_IP    VARCHAR2(300)
,       TFB_MODER_TY    VARCHAR2(300)
,       TFB_MODER_NM    VARCHAR2(300)
,       TFB_MODER_DT    DATE
,       TFB_MODER_IP    VARCHAR2(300)
,       PRIMARY KEY(TFB_SEQ)
);


COMMENT ON TABLE TM_FREE_BOARD IS '자유게시판';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_SEQ IS '게시글번호';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_TITLE_NM IS '제목';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_TEXT IS '내용';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_INPUT_TY IS '작성자타입';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_INPUT_NM IS '작성자이름';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_INPUT_DT IS '작성일';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_INPUT_IP IS '수정자IP';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_MODER_TY IS '수정자타입';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_MODER_NM IS '수정자이름';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_MODER_DT IS '수정일';
COMMENT ON COLUMN TM_FREE_BOARD.TFB_MODER_IP IS '수정자IP';


CREATE SEQUENCE "TM_TFB_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1000000 NOCACHE NOORDER NOCYCLE;





SELECT   TFB_SEQ
 ,       TFB_TITLE_NM
 ,       TFB_TEXT
 ,       TFB_INPUT_TY
 ,       TFB_INPUT_NM
 ,       TFB_INPUT_DT
 ,       TFB_INPUT_IP
 ,       TFB_MODER_TY
 ,       TFB_MODER_NM
 ,       TFB_MODER_DT
 ,       TFB_MODER_IP
FROM    TM_FREE_BOARD;


INSERT INTO TM_FREE_BOARD
(   TFB_SEQ
,   TFB_TITLE_NM
,   TFB_TEXT
,   TFB_INPUT_TY
,   TFB_INPUT_NM
,   TFB_INPUT_DT
,   TFB_INPUT_IP
,   TFB_MODER_TY
,   TFB_MODER_NM
,   TFB_MODER_DT
,   TFB_MODER_IP
)
VALUES
(   TM_TFB_SEQ.nextval
,   '제목'
,   '내용입니다.'
,   NULL
,   NULL
,   SYSDATE
,   NULL
,   NULL
,   NULL
,   SYSDATE
,   NULL
);



CREATE TABLE TM_MEMBER_TBL
(   TMT_SEQ                     NUMBER(20) NOT NULL
,   TMT_LOGIN_ID                VARCHAR2(20) NOT NULL
,   TMT_PASS_WORD               VARCHAR2(200) NOT NULL
,   TMT_MEMB_NAME               VARCHAR2(20) NOT NULL
,   TMT_MEMB_AGE                NUMBER(20)
,   TMT_MEMB_GENDER             VARCHAR2(20)
,   TMT_MEMB_EMAIL              VARCHAR2(200)
,   TMT_MEMB_BIRTH_DAY          DATE
,   TMT_MEMB_FILE               VARCHAR2(20)
,   TMT_USER_TYPE               VARCHAR2(20) DEFAULT 'user'
,   TMT_INPUT_DATE              DATE NOT NULL
,   TMT_MODER_DATE              DATE
,   PRIMARY KEY(TMT_SEQ,TMT_LOGIN_ID)
);
COMMENT ON TABLE TM_MEMBER_TBL IS '회원';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_SEQ IS '회원 번호 (PK)';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_LOGIN_ID IS '로그인 ID';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_PASS_WORD IS '비밀번호';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_MEMB_NAME IS '이름';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_MEMB_AGE IS '나이';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_MEMB_GENDER IS '성별';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_MEMB_EMAIL IS '이메일';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_MEMB_BIRTH_DAY IS '생년월일';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_MEMB_FILE IS '프로필';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_INPUT_DATE IS '생성일시';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_MODER_DATE IS '최종 수정일시';
COMMENT ON COLUMN TM_MEMBER_TBL.TMT_USER_TYPE IS '회원 등급';


ALTER TABLE TM_MEMBER_TBL ADD TMT_USER_TYPE VARCHAR2(20);

CREATE SEQUENCE "TM_TMT_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1000000 NOCACHE NOORDER NOCYCLE;



