spring:
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false


#  datasource:
##      url: jdbc:log4jdbc:oracle:thin:@ar89k9o2gxhgfodr_high?TNS_ADMIN=/Users/leedongyoung/opt/OracleCloudWallet/WVFX
#      url: jdbc:oracle:thin:@192.168.64.2:1521:xe
#      username: TODAY
#      password: Oracle12345678
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      hikari:
#        connectionTimeout: 1000
#        maximumPoolSize: 30
#        maxLifetime: 1800000
#        poolName: HikariCP
#        connection-test-query: SELECT 1 FROM dual
#        data-source-j-n-d-i: jdbc/HikariCP
#        minimum-idle: 2
#        idle-timeout: 10000


  datasource:
      url: jdbc:log4jdbc:oracle:thin:@192.168.64.2:1521:xe
      username: TODAY
      password: Oracle12345678
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      hikari:
        connectionTimeout: 1000
        maximumPoolSize: 30
        maxLifetime: 1800000
        poolName: HikariCP
        connection-test-query: SELECT 1 FROM dual
        data-source-j-n-d-i: jdbc/HikariCP
        minimum-idle: 2
        idle-timeout: 10000

#driver-class-name: oracle.jdbc.OracleDriver
#  url: jdbc:oracle:thin:@112.65.186.215:1521:testname

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: false
    jdbc-type-for-null: NULL

