spring:
  thymeleaf:
    prefix: classpath:templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    livereload:
      enabled: true



  datasource:
      url: jdbc:log4jdbc:oracle:thin:@ar89k9o2gxhgfodr_high?TNS_ADMIN=/Users/leedongyoung/opt/OracleCloudWallet/WVFX
      username: TODAY
      password: Oracle12345678
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#
#mybatis:
#  mapper-locations: classpath:mybatis/mapper/**/**.xml
#  configuration:
#    cache-enabled: false
#    jdbc-type-for-null: NULL

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: false
    jdbc-type-for-null: NULL
